[tool.poetry]
name = "Multi_tool"
version = "0.1.0"
description = ""
authors = ["zondar__ <kirito98730tkm@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pillow = "^11.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
