[tool.poetry]
name = "MultiTool"
version = "2.0.0"
description = ""
authors = ["zondar__ <kirito98730tkm@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pillow = "^11.3.0"
customtkinter = "^5.2.2"
requests = "^2.32.4"
numexpr = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
